include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Adicione regras personalizadas se necessário
    avoid_print: false  # Permitir print durante desenvolvimento
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true