// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlulzvcWFdNG1zMfSSXBt8o_CGAH7sok',
    appId: '1:111749478898:web:2670d4adadf173a5aed36b',
    messagingSenderId: '111749478898',
    projectId: 'ieadao1210',
    authDomain: 'ieadao1210.firebaseapp.com',
    storageBucket: 'ieadao1210.firebasestorage.app',
    measurementId: 'G-39VSEW2Q0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCSEqvF4i-Ew4Y5Dq5CRWo7yB4S-3J2L0',
    appId: '1:111749478898:android:afac9c2f1783068eaed36b',
    messagingSenderId: '111749478898',
    projectId: 'ieadao1210',
    storageBucket: 'ieadao1210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA301Yqn2eQdJrJCwY3srgrYOjfnNFekEI',
    appId: '1:111749478898:ios:37049959e376c34faed36b',
    messagingSenderId: '111749478898',
    projectId: 'ieadao1210',
    storageBucket: 'ieadao1210.firebasestorage.app',
    iosBundleId: 'com.example.ieadao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA301Yqn2eQdJrJCwY3srgrYOjfnNFekEI',
    appId: '1:111749478898:ios:37049959e376c34faed36b',
    messagingSenderId: '111749478898',
    projectId: 'ieadao1210',
    storageBucket: 'ieadao1210.firebasestorage.app',
    iosBundleId: 'com.example.ieadao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlulzvcWFdNG1zMfSSXBt8o_CGAH7sok',
    appId: '1:111749478898:web:2f9e5f7e34d0872eaed36b',
    messagingSenderId: '111749478898',
    projectId: 'ieadao1210',
    authDomain: 'ieadao1210.firebaseapp.com',
    storageBucket: 'ieadao1210.firebasestorage.app',
    measurementId: 'G-YWKB94KZS7',
  );

}